#!/usr/bin/env python3
"""Backfill GreedyUsedNodes / DSATURUsedNodes columns in benchmark_report.csv.

Uses ../input/<BatchName>.json (generated by build_input_graphs.py or
generate_custom_test_suite.py) and ``classical_baselines.py`` to recompute
the two classical baselines for every row whose values are currently ``NA``
or empty. Rows with existing numeric values are left untouched.

Writes the updated CSV back in place; a ``.bak`` copy is created on first
run.
"""

from __future__ import annotations

import csv
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
REPORT_DEFAULT = HERE / "results" / "benchmark_report.csv"
INPUT_DIR = REPO_ROOT / "input"
CLASSICAL = HERE / "classical_baselines.py"


def _compute(json_path: Path) -> tuple[str, str]:
    if not json_path.exists() or not CLASSICAL.exists():
        return "NA", "NA"
    try:
        out = subprocess.check_output(
            [sys.executable, str(CLASSICAL), "--json", str(json_path)],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError:
        return "NA", "NA"
    parts = out.split()
    if len(parts) != 2:
        return "NA", "NA"
    return parts[0], parts[1]


def _needs_fill(value: str) -> bool:
    if value is None:
        return True
    v = value.strip()
    return v in ("", "NA", "na", "N/A", "n/a")


def main() -> int:
    report = Path(sys.argv[1]) if len(sys.argv) > 1 else REPORT_DEFAULT
    if not report.exists():
        print(f"[ERROR] {report} not found")
        return 1

    rows: list[dict] = []
    with report.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        fieldnames = reader.fieldnames or []
        for r in reader:
            rows.append(r)

    required = {"TestName", "GreedyUsedNodes", "DSATURUsedNodes"}
    missing = required - set(fieldnames)
    if missing:
        print(f"[ERROR] missing columns in CSV: {sorted(missing)}")
        return 1

    backup = report.with_suffix(report.suffix + ".bak")
    if not backup.exists():
        shutil.copy2(report, backup)
        print(f"Backup created: {backup}")

    filled = 0
    skipped = 0
    missing_json = 0
    for r in rows:
        g = r.get("GreedyUsedNodes", "")
        d = r.get("DSATURUsedNodes", "")
        if not (_needs_fill(g) or _needs_fill(d)):
            skipped += 1
            continue

        test_name = (r.get("TestName") or "").strip()
        if not test_name:
            continue
        stem = test_name[:-5] if test_name.endswith(".yaml") else test_name
        json_path = INPUT_DIR / f"{stem}.json"
        if not json_path.exists():
            missing_json += 1
            continue

        kg, kd = _compute(json_path)
        if kg == "NA" and kd == "NA":
            missing_json += 1
            continue

        if _needs_fill(g):
            r["GreedyUsedNodes"] = kg
        if _needs_fill(d):
            r["DSATURUsedNodes"] = kd
        filled += 1

    tmp = report.with_suffix(report.suffix + ".tmp")
    with tmp.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            writer.writerow(r)
    tmp.replace(report)

    print(
        f"[backfill_baselines] filled={filled} skipped(already ok)={skipped} "
        f"missing_json={missing_json} total={len(rows)}"
    )
    print(f"  updated: {report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
